---
title: "Paper plots"
output:
  pdf_document: default
  html_document:
    df_print: paged
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = 'pdf')
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
require(ggplot2)
require(moinput)
require(rmndt)
require(quitte)
library(lucode2)
library(magpie)
library(quitte)
library(cowplot)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Set RDS files path
EJmode_all = readRDS("EJmode_all.RDS")
EJpass_all = readRDS("EJfuelsPass_all.RDS")
EJfrgt_all = readRDS("EJfuelsFrgt_all.RDS")
EJfuelsMode_all = readRDS("EJfuelsMode_all.RDS")
ESmodeabs_all = readRDS("ESmodeabs_all.RDS")
fleet_all = readRDS("fleet_all.RDS")
ESmodecap_all = readRDS("ESmodecap_all.RDS")
CO2km_int_newsales_all = readRDS("CO2km_int_newsales_all.RDS")
emidem_all = readRDS("emidem_all.RDS")
emiDemand_all = readRDS("emiDemand_all.RDS")
costs_all = readRDS("costs_all.RDS")
pref_FV_all = readRDS("pref_FV_all.RDS")
LDV_PEnew_all = readRDS("LDV_PEnew_all.RDS")
trsp_PEnew_all = readRDS("trsp_PEnew_all.RDS")
emiSec_all = readRDS("emiSec_all.RDS")

setConfig(forcecache=T)

cols <- c("NG" = "#d11141",
          "Gases" = "#d11141",
          "Gas" = "#999959",
          "Coal" = "#b2b2b2",
          "Hydro" = "#319bb6",
          "Solar" = "#ffcc00",
          "Geothermal" = "#e51900",
          "Uranium" = "#ff33ff",
          "Wind" = "#337fff",
          "Liquids" = "#8c8c8c",
          "Hybrid Liquids" = "#ffc425",
          "Hybrid Electric" = "#f37735",
          "Hybrids" = "#ffc425",
          "PHEV" = "#f37735",
          "BEV" = "#00b159",
          "Electricity" = "#00b159",
          "Electric" = "#00b159",
          "FCEV" = "#00aedb",
          "Hydrogen" = "#00aedb",
          "LDV-ICE" = "#8c8c8c",
          "LDV-PHEV" = "#f37735",
          "LDV-BEV" = "#00b159",
          "LDV-FCEV" = "#00aedb",
          "Biodiesel" = "#66a182",
          "Biomass" = "#66a182",
          "Synfuel" = "orchid",
          "Synfuels" = "orchid",
          "Oil" = "#2e4057",
          "O&M" = "#edae49",
          "Range anxiety" = "#e43f5a",
          "Refuel availability" = "#f79071",
          "Purchase" = "#d1495b",
          "Model availability" = "#58b4ae",
          "Inconvenience" = "#58b4ae",
          "Charging" = "#007892",
          "Policy-induced inconv." = "#2e4057",
          "Risk" = "#feb72b",
          "Fuel" = "#035aa6",
          "International Aviation" = "#9acd32",
          "Domestic Aviation" = "#7cfc00",
          "Aviation" = "#7cfc00",
          "Bus" = "#32cd32",
          "Passenger Rail" = "#2e8b57",
          "Freight Rail" = "#ee4000",
          "Trucks" = "#ff6a6a",
          "International Shipping" = "#cd2626",
          "Domestic Shipping" = "#ff4040",
          "Shipping" = "#ff4040",
          "Truck" = "#ff7f50",
          "Trucks (<3.5t)" = "#ff7f50",
          "Trucks (3.5t-16)" = "#8b0000",
          "Trucks (>16)" = "#fa8072",
          "Motorbikes" = "#1874cd",
          "Small Cars" = "#87cefa",
          "Large Cars" = "#6495ed",
          "Van" = " 	#40e0d0",
          "LDV" = "#00bfff",
          "Non motorized" = "#da70d6",
          "Freight"="#ff0000",
          "Freight (Inland)" = "#cd5555",
          "Inland Freight" = "#cd5555",
          "Freight Road" = "#fa8072",
          "Pass non LDV" = "#6b8e23",
          "Public land transport" = "#6b8e23",
          "Pass" = "#66cdaa",
          "Pass non LDV (Domestic)" = "#54ff9f",
          "refined liquids enduse" = "#8c8c8c",
          "FE|Transport|Hydrogen" = "#00aedb",
          "FE|Transport|NG" = "#d11141",
          "FE|Transport|Liquids" = "#8c8c8c",
          "FE|Transport|Electricity" = "#00b159",
          "FE|Transport" = "#1e90ff",
          "FE|Buildings" = "#d2b48c",
          "FE|Industry" = "#919191",
          "ElecEra" = "#00b159",
          "ElecEraWise" = "#68c6a4",
          "HydrHype" = "#00aedb",
          "HydrHypeWise" = "#o3878f",
          "ConvCase" = "#113245",
          "ConvCaseWise" = "#d11141",
          "NDC" = "#d11141",
          "NPi_Conv" = "#f6ab6c",
          "B1100_ElecPush" = "#00b159",
          "B1100_Conv" = "#113245",
          "B1100_ConvSyn" = "orchid",
          "B1100_H2Push" = "#00aedb",
          "B1100_ElecPush-LowD" = "#68c6a4",
          "B1100_Conv-LowD" = "#d11141",
          "SynSurge" = "orchid",
          "Emi|CO2|Transport|Demand" = "#113245",
          "Emi|CO2|Industry|Gross" = "#919191",
          "Emi|CO2|Buildings|Direct" = "#d2b48c",
          "Emi|CO2|Energy|Supply|Gross" = "#f2b531",
          "Emi|CO2|CDR|BECCS" = "#ed5958",
          "Emi|CO2|Land-Use Change" = "#66a182")

legend_ord_modes <- c("Freight Rail", "Truck", "Shipping", "International Shipping", "Domestic Shipping",  "Trucks", "Motorbikes", "Small Cars", "Large Cars", "Van",
                "International Aviation", "Domestic Aviation", "Aviation", "Bus", "Passenger Rail",
                "Freight", "LDV", "LDV-BEV", "LDV-PHEV", "LDV-ICE", "LDV-FCEV", "Pass non LDV", "Freight (Inland)", "Inland Freight", "Pass non LDV (Domestic)", "Public land transport", "Non motorized")

legend_ord_fuels <- c("BEV", "Electricity", "Hybrid Electric", "PHEV", "FCEV", "Hydrogen", "Hybrid Liquids", "Hybrids", "Liquids", "Oil", "Biodiesel", "Synfuel", "Synfuels", "Gases","NG")

legend_ord_costs <- c("Inconvenience", "Risk", "Charging", "Model availability", "Range anxiety", "Refuel availability", "Policy-induced inconv.","Fuel", "Purchase", "O&M")

legend_ord_emissions <- c("Emi|CO2|Industry|Gross", "Emi|CO2|Buildings|Direct", "Emi|CO2|Transport|Demand", "Emi|CO2|Energy|Supply|Gross", "Emi|CO2|Land-Use Change","Emi|CO2|CDR|BECCS")

legend_ord = c(legend_ord_modes, legend_ord_fuels, legend_ord_costs)

## mapping for scenario names
mapping_scens_paper = data.table(scenario = c("Budg1100_ConvCase", "Budg1100_ElecEra", "Budg1100_HydrHype", "Budg1100_SynSurge", "NDC_ConvCase", "NPi_ConvCase", "Budg1100_ConvCaseWise", "Budg1100_ElecEraWise"), scen_name = c("B1100_Conv", "B1100_ElecPush", "B1100_H2Push", "B1100_ConvSyn", "NDC_IC", "NPi_Conv", "B1100_Conv-LowD", "B1100_ElecPush-LowD"))

regionplot = "EUR"

## set the theme for the plots
theme2use <- theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, size=14, vjust=0.5, hjust=1),
          axis.text.y = element_text(size=14),
          axis.title.y = element_text(size=14),
          title = element_text(size=14),
          axis.line = element_line(size = 0.5, colour = "grey"),
          legend.text = element_text(size=14),
          strip.text = element_text(size=14),
          strip.background = element_rect(color = "grey"))

theme2useLargeChar <- theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, size=18, vjust=0.5, hjust=1),
          axis.text.y = element_text(size=18),
          axis.title.y = element_text(size=18),
          title = element_text(size=18),
          axis.line = element_line(size = 0.5, colour = "grey"),
          legend.text = element_text(size=18),
          strip.text = element_text(size=16),
          strip.background = element_rect(color = "grey"))


```

## Kaya decomposition

```{r, echo=FALSE, warning=FALSE, fig.width=14, fig.height=12}
kayapf = function(dtES, dtFE, dtEmi, rp, mapping){
    dtES = dtES[region == rp & mode == "pass" & year >= 2015]
    dtES = dtES[,.(demand_F = sum(demand_F)), by = .(region, year, scenario)]
    dtFE = dtFE[region == rp & year >= 2015]
    dtFE = dtFE[aggr_mode %in% c("LDV", "Pass non LDV")]
    dtFE = dtFE[,.(demand_EJ = sum(demand_EJ)), by = .(region, year, scenario)]
    
    dtEmi = dtEmi[region == rp & year >= 2015 & variable %in% c("Emi|CO2|Transport|Pass|Road|LDV|Demand", "Emi|CO2|Transport|Pass|Road|Bus|Demand", "Emi|CO2|Transport|Pass|Rail|Demand", "Emi|CO2|Transport|Pass|Aviation|Domestic|Demand", "Emi|CO2|Transport|Pass|Aviation|International|Demand"),]
    dtEmi = dtEmi[,.(value = sum(value)), by = c("region", "year", "scenario")]
    dtEmi = dtEmi[,.(year, region, scenario, emi = value)]
    
    dt = merge(dtFE, dtES, by = c("region", "year", "scenario"))
    dt[, FE_ES := demand_EJ/demand_F]
    dt = merge(dt, dtEmi, by = c("region", "year", "scenario"))
    dt[, eint := emi/demand_EJ]  ## MtCO2/EJ
    dt[, FE_ESindex := FE_ES/FE_ES[year == 2015], by = .(region, scenario)]
    dt[, ES_index := demand_F/demand_F[year == 2015], by = .(region, scenario)]
    dt[, eintindex := eint/eint[year == 2015], by = .(region, scenario)]
    dt[, emiindex := emi/emi[year == 2015], by = .(region, scenario)]
    
    dt = melt(dt[,c("region", "year", "scenario", "FE_ESindex", "ES_index", "eintindex", "emiindex")], id.vars = c("region", "year", "scenario"))
    
    dt = merge(dt, mapping, by = "scenario")
    dt = dt[scen_name %in% c("B1100_Conv", "B1100_Conv-LowD", "B1100_ElecPush", "B1100_ElecPush-LowD", "B1100_H2Push", "B1100_ConvSyn", "NPi_Conv")]
    dt[, variable := as.character(variable)]
    dt[, variable := ifelse(variable == "FE_ESindex", "B) FE per ES", variable)]
    dt[, variable := ifelse(variable == "ES_index", "A) ES", variable)]
    dt[, variable := ifelse(variable == "eintindex", "C) Emission intensity", variable)]
    dt[, variable := ifelse(variable == "emiindex", "D) Fossil emissions", variable)]
    dt[, variable := factor(variable, levels = c("A) ES", "B) FE per ES", "C) Emission intensity", "D) Fossil emissions"))] 
    p = ggplot()+
      geom_line(data = dt[year <= 2050], aes(x = year, y = value, group = scen_name, color = scen_name), size = 1.5)+
      facet_wrap(~variable, nrow = 1)+
      scale_color_manual("Scenario", values = cols)+
      labs(x = "", y = "[-]")+
      scale_x_continuous(breaks = c(2015, 2020, 2030, 2050)) +
      theme2use +
      theme(strip.text = element_text(angle = 0, hjust = 0))
    
    return(p)
  }
  
p = kayapf(dtES = ESmodecap_all, dtFE = EJmode_all, dtEmi = emiDemand_all, rp = regionplot, mapping_scens_paper)
  
p

aspect_ratio <- 3
height <- 4
## indexed to 2015
ggsave("kayatransport.png", p, dpi=500, height = height , width = height * aspect_ratio)


```

## Costs detailed

```{r, echo=FALSE, warning=FALSE, fig.width=14, fig.height=12}
costspf = function(dt, rp, mapping_scens){
    dt = dt[region == rp & scenario %in% c("Budg1100_ConvCase", "Budg1100_ElecEra","Budg1100_HydrHype", "NPi_ConvCase") & year %in% c(2020, 2030, 2050)]
    map = data.table(name = c("Risk", "Charging", "Model availability", "Range anxiety", "Refuel availability", "Fuel", "Policy-induced inconv.", "Purchase", "O&M"),
    logit_type = c("prisk", "pchar", "pmod_av", "prange", "pref", "fuel_price", "pinco_tot", "purchase", "other"),
    type = c("inc", "inc", "inc", "inc", "inc", "real", "inc", "real", "real"))
    dt = merge(dt, map, by = "logit_type")

    dt[technology == "Hybrid Electric", technology := "PHEV"]
    dt[technology == "Hybrid Liquids", technology := "Hybrids"]


    dt_inc = dt[type == "inc"]
    dt_inc = dt_inc[,.(cost = sum(cost)), by = c("region", "year", "type", "technology", "scenario")]
    dt_inc = dt_inc[, c("name", "logit_type") := list("Inconvenience", "pinc")]

    dt_tot = rbind(dt_inc, dt[type == "real"])
    dt_tot[, name := factor(name, levels = legend_ord)]
    dt_tot[, alph := ifelse(logit_type=="pinc", 0.6, 0.9)]

    dt_tot = merge(dt_tot, mapping_scens, by = "scenario")
    dt_tot[, scen_name := ifelse(is.na(scen_name), scenario, scen_name)]
    ## define the maximum on the y-axis depending on the maximum value across scenarios
    dt_tot = dt_tot[, sum := sum(cost), by = c("year", "scenario", "region", "technology")]
    dt_tot[, maxval := max(sum)]

    plot_hist = ggplot()+
      geom_bar(data = dt_tot[year == 2020 & scen_name == "NPi_Conv"][,scen_name := "Historical"], aes(x = technology, y = cost, group = name, fill = name, alpha = alph), position = "stack", stat = "identity")+
      ylim(0, 1.01*unique(dt_tot[, maxval]))+
      facet_wrap(~year+scen_name, nrow = 1)+
      theme2use +
      scale_fill_manual(values = cols)+
      labs(y = "[$/pkm]", x="")+
      scale_alpha(range=c(0.4,1)) +
      guides(alpha=FALSE,
             linetype=FALSE,
             fill=guide_legend(reverse=TRUE, title="Cost component"))+
      theme(legend.position = "none",
            axis.text.x = element_text(angle = 90, size=18, vjust=0.5, hjust=1),
            axis.text.y = element_text(size=18),
            axis.title.y = element_text(size=18),
            strip.text = element_text(size=16))


    plot_proj = ggplot()+
      geom_bar(data = dt_tot[year %in% c(2030, 2050) & scen_name != "NPi_Conv"], aes(x = technology, y = cost, group = name, fill = name, alpha = alph), position = "stack", stat = "identity") +
      facet_wrap(~year+scen_name, nrow = 1)+
      theme2use +
      ylim(0,1.01*unique(dt_tot[, maxval]))+
      scale_fill_manual(values = cols)+
      labs(y = "[$/pkm]", x="")+
      scale_alpha(range=c(0.4,1)) +
      guides(alpha=FALSE,
             linetype=FALSE,
             fill=guide_legend(reverse=TRUE, title="Cost component"))+
      theme(axis.title.y = element_blank(),
            axis.text.y = element_blank(),
            axis.text.x = element_text(angle = 90, size=18, vjust=0.5, hjust=1),
            legend.text = element_text(size=18),
            legend.title = element_text(size=18),
            strip.text = element_text(size=16))


    ## get legend of plots
    techlegend_allcosts <- get_legend(plot_proj)

    plot_proj = plot_proj+
    theme(legend.position = "none")

    ## combine all elements in final plot
    plot_allcosts = plot_grid(plot_hist, plot_proj, align = "h", ncol = 2, rel_widths  = c(0.2, 0.8))


    ## inconvenience costs only
    dt_inc = dt[type == "inc"]
    dt_inc[, name := factor(name, levels = legend_ord)]
    dt_inc = merge(dt_inc, mapping_scens, by = "scenario")
    dt_inc[, scen_name := ifelse(is.na(scen_name), scenario, scen_name)]
    ## define the maximum on the y-axis depending on the maximum value across scenarios
    dt_inc = dt_inc[, sum := sum(cost), by = c("year", "scenario", "region", "technology")]
    dt_inc[, maxval := max(sum)]


    plot_hist = ggplot()+
      geom_bar(data = dt_inc[year == 2020 & scen_name == "NPi_Conv"][,scen_name := "Historical"], aes(x = technology, y = cost, group = name, fill = name), position = "stack", stat = "identity")+
      ylim(0, 1.01*unique(dt_inc[, maxval]))+
      facet_wrap(~year+scen_name, nrow = 1)+
      theme2use +
      scale_fill_manual(values = cols)+
      labs(y = "[$/pkm]", x="")+
      guides(alpha=FALSE,
             linetype=FALSE,
             fill=guide_legend(reverse=TRUE, title="Cost component"))+
      theme(legend.position = "none",
            axis.text.x = element_text(angle = 90, size=18, vjust=0.5, hjust=1),
            axis.text.y = element_text(size=18),
            axis.title.y = element_text(size=18),
            strip.text = element_text(size=16))


    plot_proj = ggplot()+
      geom_bar(data = dt_inc[year %in% c(2030, 2050)& scen_name != "NPi_Conv"], aes(x = technology, y = cost, group = name, fill = name), position = "stack", stat = "identity") +
      facet_wrap(~year+scen_name, nrow = 1)+
      theme2use +
      ylim(0,1.01*unique(dt_inc[, maxval]))+
      scale_fill_manual(values = cols)+
      labs(y = "[$/pkm]", x="")+
      scale_alpha(range=c(0.4,1)) +
      guides(alpha=FALSE,
             linetype=FALSE,
             fill=guide_legend(reverse=TRUE, title="Cost component"))+
      theme(axis.title.y = element_blank(),
            axis.text.y = element_blank(),
            axis.text.x = element_text(angle = 90, size=18, vjust=0.5, hjust=1),
            legend.text = element_text(size=18),
            legend.title = element_text(size=18),
            strip.text = element_text(size=16))

    ## get legend of plots
    techlegend_detailed <- get_legend(plot_proj)

    plot_proj = plot_proj+
    theme(legend.position = "none")

    ## combine all elements in final plot
    plot_detailed = plot_grid(plot_hist, plot_proj, align = "h", ncol = 2, rel_widths  = c(0.2,0.8))

    ## combine all costs and detailed
    plot = plot_grid(plot_allcosts, plot_detailed, align = "v", nrow = 2)
    legends = plot_grid(techlegend_allcosts, techlegend_detailed, align = "v", ncol = 1)
    plot = plot_grid(plot, legends, align = "h", ncol = 2, rel_widths  = c(0.8,0.2))



    return(plot)
}

p = costspf(costs_all, rp = regionplot, mapping_scens_paper)

p

aspect_ratio <- 1.2
height <- 14

ggsave("LDVtotcost_selectedscen.png", p, dpi=300, height = height , width = height * aspect_ratio)
```
## Costs for 2015

```{r, echo=FALSE, warning=FALSE, fig.width=14, fig.height=12}

costs_detailed_pf = function(dt, rp, mapping_scens){
    dt = dt[region == rp & scenario %in% c("NPi_ConvCase") & year %in% c(2015)]
    dt[technology == "Hybrid Electric", technology := "PHEV"]
    dt[technology == "Hybrid Liquids", technology := "Hybrids"]

    map = data.table(name = c("Risk", "Charging", "Model availability", "Range anxiety", "Refuel availability", "Fuel", "Policy-induced inconv.", "Purchase", "O&M"),
    logit_type = c("prisk", "pchar", "pmod_av", "prange", "pref", "fuel_price", "pinco_tot", "purchase", "other"),
    type = c("inc", "inc", "inc", "inc", "inc", "real", "inc", "real", "real"))
    dt_tot = merge(dt, map, by = "logit_type")
    dt_tot[, alph := ifelse(type == "inc", 0.5, 0.9)]

    dt_tot = merge(dt_tot, mapping_scens, by = "scenario")
    dt_tot[, scen_name := ifelse(is.na(scen_name), scenario, scen_name)]
    ## define the maximum on the y-axis depending on the maximum value across scenarios
    dt_tot = dt_tot[, sum := sum(cost), by = c("year", "scenario", "region", "technology")]
    ## remove policy induced inconvenience cost (this plot represents only calibrated values)
    dt_tot = dt_tot[name != "Policy-induced inconv."]
    dt_tot[, maxval := max(sum)]
    dt_tot[, name := factor(name, levels = c("Risk", "Charging", "Model availability", "Range anxiety", "Refuel availability", "Fuel", "Purchase", "O&M"))]
    

    plot = ggplot()+
      geom_bar(data = dt_tot[year == 2015 & scen_name == "NPi_Conv"], aes(x = technology, y = cost, group = name, fill = name, alpha = alph), position = "stack", stat = "identity")+
      facet_wrap(~year, nrow = 1)+
      theme2use +
      ylim(0,1.01*unique(dt_tot[, maxval]))+
      scale_fill_manual(values = cols)+
      labs(y = "[$/pkm]", x="")+
      scale_alpha(range=c(0.6,1)) +
      guides(alpha=FALSE,
             linetype=FALSE,
             fill=guide_legend(reverse=TRUE, title="Cost component"))+
      coord_flip()

     return(plot)
}

p = costs_detailed_pf(costs_all, rp = regionplot, mapping_scens_paper)

p

aspect_ratio <- 2
height <- 3

ggsave("LDVtotcost_histoverview.png", p, dpi=300, height = height , width = height * aspect_ratio)


```





## LDVs fleet

```{r, echo=FALSE, warning=FALSE, fig.width=14, fig.height=12}
fleetcomparisonArea_regi_pf = function(dt, rp, mapping){
  dt_sales = dt[variable == "newdem"]
  dt_sales = dt_sales[,.(value = sum(value)), by = .(region, year, technology, scenario)]
  dt_sales[, variable := "Sales"]
  dt = dt[,.(value = sum(value)), by = .(region, year, technology, scenario)]
  dt[, variable := "Stock"]
  dt = rbind(dt_sales, dt)
  dt = merge(dt, mapping)
  dt[technology == "Hybrid Electric", technology := "PHEV"]
  dt[technology == "Hybrid Liquids", technology := "Hybrids"]
  dt = dt[scen_name %in% c("NPi_Conv", "B1100_Conv", "B1100_ElecPush", "B1100_H2Push", "B1100_ConvSyn", "B1100_Conv-LowD", "B1100_ElecPush-LowD")]
  dt[, scen_name := factor(scen_name, levels = c("NPi_Conv", "B1100_Conv", "B1100_ConvSyn", "B1100_H2Push", "B1100_ElecPush", "B1100_Conv-LowD", "B1100_ElecPush-LowD"))]
  dt[, technology := factor(technology, levels = c("BEV", "PHEV", "FCEV", "Hybrids", "NG", "Liquids"))]
  dt[, variable := factor(variable, levels = c("Stock", "Sales"))]

  parea = ggplot()+
    geom_area(data = dt[region == rp & year >= 2020 & year <= 2050], aes(x=year, y=value, fill = technology, group = technology), alpha = 0.9, color="black", size=0.05, position= position_stack())+
  facet_grid(variable ~ scen_name, scales = "free_y", switch = "y")+
        scale_fill_manual("Technology",values = cols, breaks=legend_ord)+
    expand_limits(y = c(0,1))+
    labs(x = "", y = "[million veh]")+
    scale_x_continuous(breaks = c(2020, 2030, 2050)) +
    theme2useLargeChar +
    theme(strip.placement = "outside",
    strip.background.y=element_rect(color = NA,  fill=NA),
    strip.text.y = element_text(size = 19))

   return(parea)
}

p = fleetcomparisonArea_regi_pf(fleet_all, rp = regionplot, mapping = mapping_scens_paper)

p


aspect_ratio <- 2.5
height <- 8
ggsave("pfleetArea.png", p, dpi=300, height = height , width = height * aspect_ratio)
```

## New additions to the LDV fleet: Sales 

```{r, echo=FALSE, warning=FALSE, fig.width=14, fig.height=12}
salescomparisonArea_regi_pf = function(dt, rp, mapping){
  dt = dt[variable == "newdem"]
  dt = dt[,.(value = sum(value)), by = .(region, year, technology, scenario)]
  dt = merge(dt, mapping)
  dt = dt[scen_name %in% c("NPi_Conv", "B1100_Conv", "B1100_ElecPush", "B1100_H2Push", "B1100_ConvSyn", "B1100_Conv-LowD", "B1100_ElecPush-LowD")]
  dt[, scen_name := factor(scen_name, levels = c("NPi_Conv", "B1100_Conv", "B1100_ElecPush", "B1100_H2Push", "B1100_ConvSyn", "B1100_Conv-LowD", "B1100_ElecPush-LowD"))]
  dt[technology == "Hybrid Electric", technology := "PHEV"]
  dt[technology == "Hybrid Liquids", technology := "Hybrids"]
  dt[, technology := factor(technology, levels = c("BEV", "PHEV", "FCEV", "Hybrids", "NG", "Liquids"))]

  parea = ggplot()+
    geom_area(data = dt[region == rp & year >= 2020 & year <= 2050], aes(x=year, y=value, fill = technology, group = technology), alpha = 0.9, color="black", size=0.05, position= position_stack())+
  facet_wrap(~scen_name, nrow = 1)+
        scale_fill_manual("Technology",values = cols, breaks=legend_ord)+
    expand_limits(y = c(0,1))+
    labs(x = "", y = "[million veh]")+
    scale_x_continuous(breaks = c(2020, 2030, 2050)) +
    theme2use+
    theme(legend.position = "none")

  dt = dt[year %in% c(2030, 2050) & region == rp]

  ## define the maximum on the y-axis depending on the maximum value across scenarios
  pbar = ggplot()+
    geom_bar(data = dt,
             aes(x=scen_name, y=value, group=technology,
                 fill = technology, width=.75), position="stack", stat = "identity", width = 0.5, alpha = 0.9)+
    theme2use +
    labs(x = "", y = "[million veh]")+
    facet_wrap(~ year)+
    guides(fill=guide_legend(title="Powertrain"))+
    scale_fill_manual(values = cols)

   plot = plot_grid(parea, pbar, align = "v", ncol = 1, rel_heights  = c(0.4, 0.6))
   return(plot)
}

p = salescomparisonArea_regi_pf(fleet_all, rp = regionplot, mapping = mapping_scens_paper)

p

aspect_ratio <- 2
height <- 8
ggsave("psalesArea.png", p, dpi=350, height = height , width = height * aspect_ratio)
```


## Trend of preference factors for Buses and Trucks

```{r, echo=FALSE, warning=FALSE}
prefBusTrucksplotf = function(pref, mapping){
pref = pref[iso=="USA" & technology %in% c("Electric", "FCEV") & vehicle_type %in% c("Bus_tmp_vehicletype", "Truck (0-2.7t)")]
pref = pref[year >= 2020 & year <= 2050]
pref[, vehicle_type := ifelse(vehicle_type == "Bus_tmp_vehicletype", "Large Trucks and Buses", "Small Trucks")]

pref = merge(pref, mapping, by = "scenario")

p = ggplot()+
  geom_line(data = pref[scen_name %in% c("B1100_ElecPush", "B1100_H2Push", "B1100_Conv")], aes(x = year, y = value, group = interaction(technology, vehicle_type), color = technology, linetype = vehicle_type))+
  facet_wrap(~scen_name, ncol = 3)+
  theme2use +
  theme(axis.text.x = element_text(angle = 90, size=5, vjust=0.5, hjust=1),
        axis.text.y = element_text(size=5),
        axis.title.y = element_text(size=5),
        title = element_text(size=5),
        legend.text = element_text(size=5),
        strip.text = element_text(size=5))+
  labs(y = "Preference factor [-]", x="")+
  scale_color_manual("Technology", values = cols,labels = c("Electric", "FCEV"))+
  scale_linetype_manual("Vehicle", values = c(1,2),
                        labels = c("Large Trucks and Buses", "Small Trucks"))
return(p)
}
p = prefBusTrucksplotf(pref_FV_all, mapping_scens_paper)
p
aspect_ratio <- 2
height <- 2
ggsave("buses_trucks_SW.png", p, dpi=500, height = height , width = height * aspect_ratio)
```


## PE in transport by fuel
## LDV PE new version

```{r, echo=FALSE, warning=FALSE}
LDV_PEnewpf = function(dt, rp, mapping){
   dt = dt[region == rp]
   dt = merge(dt, mapping, by = "scenario")
   dt[, year := as.numeric(year)]
   dt = dt[year >= 2020 & year <= 2050]
   dt[, scen_name := factor(scen_name, levels = c("NPi_Conv", "B1100_Conv", "B1100_ConvSyn", "B1100_H2Push", "B1100_ElecPush", "B1100_Conv-LowD", "B1100_ElecPush-LowD"))]
   p = ggplot()+
        geom_area(data = dt, aes(x = year, y = value, fill = technology, group = technology))+
        facet_wrap(~scen_name, nrow = 1)+
  labs(y = "[EJ]", x="")+
  scale_fill_manual("Source", values = cols)+
  scale_x_continuous(breaks = c(2020, 2030, 2050))+
  theme2useLargeChar

  return(p)
}


p = LDV_PEnewpf(LDV_PEnew_all, rp = regionplot, mapping_scens_paper)
print("LDVs have their share of synfuels")

aspect_ratio <- 5
height <- 4
ggsave("LDV_PEnew.png", p, dpi=500, height = height , width = height * aspect_ratio)
```


```{r, echo=FALSE, warning=FALSE}
trsp_PEnewpf = function(dt, rp, mapping){
   dt = dt[region == rp]
   dt = merge(dt, mapping, by = "scenario")
   dt[, year := as.numeric(year)]
   dt = dt[year >= 2020 & year <= 2050]
   dt[, scen_name := factor(scen_name, levels = c("NPi_Conv", "B1100_Conv", "B1100_ConvSyn", "B1100_H2Push", "B1100_ElecPush", "B1100_Conv-LowD", "B1100_ElecPush-LowD"))]
   p = ggplot()+
        geom_area(data = dt, aes(x = year, y = value, fill = technology, group = technology))+
        facet_wrap(~scen_name, nrow = 1)+
  labs(y = "[EJ]", x="")+
  scale_fill_manual("Source", values = cols)+
  scale_x_continuous(breaks = c(2020, 2030, 2050))+
  theme2useLargeChar

  return(p)
}


p = trsp_PEnewpf(trsp_PEnew_all, rp = regionplot, mapping_scens_paper)
print("LDVs have their share of synfuels")

aspect_ratio <- 5
height <- 4
ggsave("trsp_PEnew.png", p, dpi=500, height = height , width = height * aspect_ratio)
```
## PE in HDVs by fuel

## CO2 intensity of LDV sales

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=14, fig.height=12}

CO2km_int_EUR_newsalespf = function(dt, rp = "EUR", mapping){
  dt = dt[!is.na(gCO2_km_ave)]
    ## add historical values
  historical_values = data.table(year = c(2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018), emi = c(159, 157, 145, 140, 137, 132, 128, 124, 120, 119, 119, 120))

  targets = data.table(name = c("2021 target", "2025 target", "2030 target"), value = c(95, 95*(1-0.15), 95*(1-0.37)))

  dt = merge(dt, mapping, by = "scenario")

   plot = ggplot()+
    geom_line(data = dt[year >= 2020 & year <= 2050 & region == rp], aes(x = year, y = gCO2_km_ave, group = scen_name, color = scen_name))+
    geom_point(data = historical_values, aes(x = year, y = emi), color = "grey20")+
    geom_point(data = targets, aes(x = c(2021, 2025, 2030), y = value, shape = name), color = "grey20", alpha = 0.5, size = 2)+
    geom_text(data = targets, aes(y = value+5, x = c(2021, 2025, 2030), label = name), size = 4)+
    labs(y = expression(paste("[", gCO["2"], "/km]")), x = "")+
    expand_limits(y = c(0,1))+
    scale_x_continuous(breaks = c(2010, 2020, 2030, 2050))+
    theme2use +
    guides(shape = FALSE)+
    scale_color_manual("Scenario", values = cols)

  return(plot)
}

p = CO2km_int_EUR_newsalespf(CO2km_int_newsales_all, mapping = mapping_scens_paper)

p

aspect_ratio <- 1.5
height <- 4
ggsave("pCO2int.png", p, dpi=500, height = height , width = height * aspect_ratio)
```


## Tailpipe (only fossil fuels) emissions

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=14, fig.height=12}
emiDemand_pf = function(dt, rp, mapping){
 dt = dt[year <= 2050 & region == rp]
 dt[, scenario := as.character(scenario)]
 dt = dt[variable %in% c("Emi|CO2|Transport|Pass|Road|LDV|Demand", "Emi|CO2|Transport|Freight|Rail|Demand", "Emi|CO2|Transport|Freight|Road|Demand", "Emi|CO2|Transport|Pass|Aviation|Domestic|Demand", "Emi|CO2|Transport|Pass|Aviation|International|Demand", "Emi|CO2|Transport|Pass|Road|Bus|Demand", "Emi|CO2|Transport|Pass|Rail|Demand", "Emi|CO2|Transport|Freight|International Shipping|Demand", "Emi|CO2|Transport|Freight|Navigation|Demand")]
 dt[, mode := "mode"]
 dt[grepl("LDV", variable), mode := "LDV"]
 dt[grepl("Freight\\|Road|Freight\\|Rail", variable), mode := "Inland Freight"]
 dt[grepl("Bus|Pass\\|Rail", variable), mode := "Public land transport"]
 dt[grepl("Aviation", variable), mode := "Aviation"]
 dt[grepl("Shipping|Navigation", variable), mode := "Shipping"]
 dt = dt[,.(value = sum(value)), by = c("region","year","scenario", "mode")]
 dt[, mode := factor(mode, levels = legend_ord)]
 dt = merge(dt, mapping, by = "scenario")
 dt[, scen_name := factor(scen_name, levels = c("NPi_Conv", "B1100_Conv", "B1100_ConvSyn", "B1100_H2Push", "B1100_ElecPush", "B1100_Conv-LowD", "B1100_ElecPush-LowD"))]
  plot1 = ggplot()+
    geom_area(data = dt, aes(x = year, y = value, group = mode, fill = mode), alpha = 0.9, color="black", size=0.05, position= position_stack())+
    labs(y = expression(paste("[Mt", CO["2"], "]")), x = "")+
    facet_grid(~scen_name) +
    scale_x_continuous(breaks = c(2010, 2020, 2030, 2050))+
    theme2useLargeChar +
    guides(shape = FALSE)+
    scale_fill_manual("Transport mode", values = cols)


 dt = dt[,.(value = sum(value)), by = .(scen_name, year)]
 dt = dt[year>=2020]
 plot2 = ggplot()+
    geom_line(data = dt, aes(x = year, y = value, group = scen_name, color = scen_name), size=1)+
    scale_x_continuous(breaks = c(2020, 2030, 2050))+
    theme2use +
    labs(x = "", y = expression(paste("[Mt", CO["2"], "]")), title = "Demand emissions, transport sector")+
    guides(shape = FALSE) +
    scale_color_manual("Scenario", values = cols)

 plot = list(plot1 = plot1, plot2 = plot2)

  return(plot)
}

p = emiDemand_pf(emiDemand_all, regionplot, mapping = mapping_scens_paper)

p
aspect_ratio <- 5.1
height <- 4
ggsave("emiDemand_mode.png", p$plot1, dpi=500, height = height , width = height * aspect_ratio)

aspect_ratio <- 1.5
height <- 4

ggsave("emiDemandLine.png", p$plot2, dpi = 200, height = height , width = height * aspect_ratio)
```

## Final energy, by mode

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=14, fig.height=12}
EJmodepf = function(dt, rp,  mapping){
  dt = dt[year >= 2020 & year <= 2050 & region == rp]
  dt[, mode := "mode"]
  dt[vehicle_type_plot %in% c("Small Cars", "Large Cars", "Motorbikes"), mode := "LDV"]
  dt[vehicle_type_plot %in% c("International Shipping", "Domestic Shipping"), mode := "Shipping"]
  dt[vehicle_type_plot %in% c("International Aviation", "Domestic Aviation"), mode := "Aviation"]
  dt[vehicle_type_plot %in% c("Truck", "Freight Rail"), mode := "Inland Freight"]
  dt[vehicle_type_plot %in% c("Bus", "Passenger Rail"), mode := "Public land transport"]
  dt = dt[,.(value = sum(demand_EJ)), by = c("region","year","scenario", "mode")]
  dt[, mode := factor(mode, levels = legend_ord)]
  dt = merge(dt, mapping, by = "scenario")
  dt[, scen_name := factor(scen_name, levels = c("NPi_Conv", "B1100_Conv", "B1100_ConvSyn", "B1100_H2Push", "B1100_ElecPush", "B1100_Conv-LowD", "B1100_ElecPush-LowD"))]
  plot = ggplot()+
    geom_area(data = dt, aes(x=year, y=value, group = mode, fill = mode), color = "black", size=0.05, position= position_stack())+
    labs(x = "", y = "[EJ]")+
    facet_grid(~scen_name)+
    scale_fill_manual("Transport mode", values = cols, breaks = legend_ord)+
    expand_limits(y = c(0,1))+
    scale_x_continuous(breaks = c(2020,2030,2050, 2100)) +
    theme2useLargeChar

  return(plot)
}

p = EJmodepf(EJmode_all, regionplot, mapping = mapping_scens_paper)
aspect_ratio <- 5.1
height <- 4
ggsave("FEmode.png", p, dpi=500, height = height , width = height * aspect_ratio)
```


## Final energy, by fuel

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=14, fig.height=12}
## passenger by fuel
EJfuelsMode_pf = function(dt, rp, mapping){
  dt = dt[year >= 2020 & year <= 2050 & region == rp]
  dt = merge(dt, mapping, by = "scenario")
  dt[, scen_name := factor(scen_name, levels = c("NPi_Conv", "B1100_Conv", "B1100_ConvSyn", "B1100_H2Push", "B1100_ElecPush", "B1100_Conv-LowD", "B1100_ElecPush-LowD"))]
  plotLDV = ggplot()+
    geom_area(data = dt[subsec == "LDV"], aes(x=year, y=demand_EJ, group = subtech, fill = subtech), color="black", size=0.05, position= position_stack())+
    labs(x = "", y = "[EJ]")+
    facet_grid(~scen_name)+
    scale_fill_manual("Technology",values = cols, breaks=legend_ord)+
    expand_limits(y = c(0,1))+
    scale_x_continuous(breaks = c(2020, 2030, 2050)) +
    theme2useLargeChar

  plotFreight = ggplot()+
    geom_area(data = dt[subsec == "Freight"], aes(x=year, y=demand_EJ, group = subtech, fill = subtech), color="black", size=0.05, position= position_stack())+
    labs(x = "", y = "[EJ]")+
    facet_grid(~scen_name)+
    scale_fill_manual("Technology",values = cols, breaks=legend_ord)+
    expand_limits(y = c(0,1))+
    scale_x_continuous(breaks = c(2020, 2030,2050, 2100)) +
    theme2useLargeChar
  
  dt_all = dt[,.(demand_EJ = sum(demand_EJ)), by =.(region, year, subtech, scen_name)]
  plotAllT = ggplot()+
    geom_area(data = dt_all, aes(x=year, y=demand_EJ, group = subtech, fill = subtech), color="black", size=0.05, position= position_stack())+
    labs(x = "", y = "[EJ]")+
    facet_grid(~scen_name)+
    scale_fill_manual("Technology",values = cols, breaks=legend_ord)+
    expand_limits(y = c(0,1))+
    scale_x_continuous(breaks = c(2020, 2030,2050)) +
    theme2useLargeChar

  plot = list(plotLDV = plotLDV, plotFreight = plotFreight, plotAllT = plotAllT)
  return(plot)
}

p = EJfuelsMode_pf(dt = EJfuelsMode_all, rp = regionplot, mapping = mapping_scens_paper)

pLDV = p$plotLDV
pfre = p$plotFreight
pAllT = p$plotAllT

aspect_ratio <- 5
height <- 4
ggsave("FEfuelModeLDV.png", pLDV, dpi=500, height = height , width = height * aspect_ratio)
ggsave("FEfuelModeFreight.png", pfre, dpi=500, height = height , width = height * aspect_ratio)
ggsave("FEfuelModeAllT.png", pAllT, dpi=500, height = height , width = height * aspect_ratio)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=14, fig.height=12}
ESmodepf = function(dt, rp, mapping){
  dt = dt[region == rp & year >= 2020 & year <= 2050]
  dt[, vehicle_type_plot := factor(vehicle_type_plot, levels = legend_ord)]
  dt = merge(dt, mapping, by = "scenario")
  dt[, scen_name := factor(scen_name, levels = c("NPi_Conv", "B1100_Conv", "B1100_ConvSyn", "B1100_H2Push", "B1100_ElecPush", "B1100_Conv-LowD", "B1100_ElecPush-LowD"))]
  dt_freight = dt[mode == "freight"]
  dt_freight = dt_freight[, .(demand_F = sum(demand_F)), by = c("region", "year", "vehicle_type_plot", "scen_name")]
  plot_frgt = ggplot()+
    geom_area(data = dt_freight, aes(x=year, y=demand_F, group = vehicle_type_plot, fill = vehicle_type_plot), color="black", size=0.05, position= position_stack())+
    labs(x = "", y = "[trillion tkm]")+
    facet_grid(~scen_name)+
    scale_fill_manual("Transport mode",values = cols, breaks=legend_ord)+
    expand_limits(y = c(0,1))+
    scale_x_continuous(breaks = c(2020,2030,2050))+
    theme2useLargeChar

  dt_pass = dt[mode == "pass"]
  dt_pass[technology %in% c("Hybrid Liquids", "Liquids"), technology := "ICE"]
  dt_pass[technology %in% c("Hybrid Electric"), technology := "PHEV"]
  
  dt_pass[vehicle_type_plot %in% c("Large Cars", "Small Cars", "Motorbikes"), vehicle_type_plot := paste0("LDV-", technology)]
  dt_pass[vehicle_type_plot %in% c("Bus", "Passenger Rail"), vehicle_type_plot := "Public land transport"]
  dt_pass[grepl("Aviation", vehicle_type_plot), vehicle_type_plot := "Aviation"]
  dt_pass = dt_pass[, .(demand_F = sum(demand_F)), by = c("region", "year", "vehicle_type_plot", "mode", "scen_name")]

  plot_pass = ggplot()+
    geom_area(data = dt_pass, aes(x=year, y=demand_F, group = vehicle_type_plot, fill = vehicle_type_plot), color="black", size=0.05, position= position_stack())+
    labs(x = "", y = "[trillion pkm]")+
    facet_grid(~scen_name)+
    scale_fill_manual("Transport mode",values = cols, breaks=legend_ord)+
    expand_limits(y = c(0,1))+
    scale_x_continuous(breaks = c(2020,2030,2050))+
    theme2useLargeChar


    return(list(plot_pass = plot_pass, plot_frgt = plot_frgt))
}


p = ESmodepf(ESmodeabs_all, regionplot, mapping = mapping_scens_paper)
p
ppass = p$plot_pass
pfre = p$plot_frgt
aspect_ratio <- 5.2
height <- 4
ggsave("ESModePass.png", ppass, dpi=500, height = height , width = height * aspect_ratio)
ggsave("ESModeFr.png", pfre, dpi=500, height = height , width = height * aspect_ratio)

```
## Emissions by sector

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=14, fig.height=12}
emiSecpf = function(dt, rp, mapping){
  dt = dt[region == rp & year >= 2020 & year <= 2050]
  labels_components = c("Emi|CO2|CDR|BECCS" = "BECCS",
                        "Emi|CO2|Land-Use Change" = "Landuse",
                        "Emi|CO2|Energy|Supply|Gross" = "Supply",
                        "Emi|CO2|Industry|Gross" = "Industry",
                        "Emi|CO2|Transport|Demand" = "Transport",
                        "Emi|CO2|Buildings|Direct" = "Buildings")
  dt = merge(dt, mapping, by = "scenario")
  dt[, scen_name := factor(scen_name, levels = c("NPi_Conv", "B1100_Conv", "B1100_ConvSyn", "B1100_H2Push", "B1100_ElecPush", "B1100_Conv-LowD", "B1100_ElecPush-LowD"))]

  
  plot = ggplot()+
    geom_bar(data = dt[year>=2020], aes(x=year, y=value, fill = varplot, group=varplot), position="stack", stat = "identity")+
    scale_fill_manual("Component", values = cols, breaks = legend_ord_emissions, labels = labels_components)+
    facet_grid(~scen_name)+
    labs(title = expression(paste(CO["2"], " emissions relevant sectors ")), y = expression(paste("[Mt", CO["2"], "/year]")), x = "")+
    theme2use+
    expand_limits(y = c(0,1))+
    scale_x_continuous(breaks = c(2020,2030,2050))

  return(plot)
}

p = emiSecpf(emiSec_all, regionplot, mapping = mapping_scens_paper)
p
aspect_ratio <- 5.05
height <- 4
ggsave("emiSec.png", p, dpi=500, height = height , width = height * aspect_ratio)
```
