*** SOF ./modules/45_carbonprice/exogenous/input/p45_tau_co2_tax.inc
*======================================================*
*=              Exogenous CO2 tax level               =*
*======================================================*
*= author:                                            =*
*= date  :                                            =*
*= generated with r_gen_co2_tax.r                     =*
*= units: 10^12 US$(2005)/GtC                         =*
*======================================================*

p45_tau_co2_tax(t,regi)=0;

*** EOF ./modules/45_carbonprice/exogenous/input/p45_tau_co2_tax.inc
