*** SOF ./modules/15_climate/magicc/input/p15_emicapglob.inc
pm_emicapglob("2005") =   7.471 ;
pm_emicapglob("2010") =   8.04  ;
pm_emicapglob("2015") =   7.557 ;
pm_emicapglob("2020") =   7.07  ;
pm_emicapglob("2025") =   6.189 ;
pm_emicapglob("2030") =   5.31  ;
pm_emicapglob("2035") =   4.904 ;
pm_emicapglob("2040") =   4.50  ;
pm_emicapglob("2045") =   4.053 ;
pm_emicapglob("2050") =   3.61  ;
pm_emicapglob("2055") =   3.252 ;
pm_emicapglob("2060") =   2.90  ;
pm_emicapglob("2065") =   2.641 ;
pm_emicapglob("2070") =   2.38  ;
pm_emicapglob("2075") =   2.065 ;
pm_emicapglob("2080") =   1.75  ;
pm_emicapglob("2085") =   1.497 ;
pm_emicapglob("2090") =   1.25  ;
pm_emicapglob("2095") =   1.091 ;
pm_emicapglob("2100") =   0.93  ;
pm_emicapglob("2105") =   0.872 ;
pm_emicapglob("2110") =   0.81  ;
pm_emicapglob("2115") =   0.802 ;
pm_emicapglob("2120") =   0.79  ;
pm_emicapglob("2125") =   0.806 ;
pm_emicapglob("2130") =   0.82  ;
pm_emicapglob("2135") =   0.844 ;
pm_emicapglob("2140") =   0.87  ;
pm_emicapglob("2145") =   0.897 ;
pm_emicapglob("2150") =   0.93  ;

*** EOF ./modules/15_climate/magicc/input/p15_emicapglob.inc
