*** SOF ./modules/15_climate/magicc/input/p15_emicapglob_450.inc
pm_emicapglob("2005") = 7.471  ;
pm_emicapglob("2010") =  8.373 ;
pm_emicapglob("2015") =  8.698 ;
pm_emicapglob("2020") =  8.360 ;
pm_emicapglob("2025") =  7.508 ;
pm_emicapglob("2030") =  6.559 ;
pm_emicapglob("2035") =  5.743 ;
pm_emicapglob("2040") =  4.861 ;
pm_emicapglob("2045") =  4.014 ;
pm_emicapglob("2050") =  3.499 ;
pm_emicapglob("2055") =  3.058 ;
pm_emicapglob("2060") =  2.704 ;
pm_emicapglob("2065") =  2.479 ;
pm_emicapglob("2070") =  2.114 ;
pm_emicapglob("2075") =  1.880 ;
pm_emicapglob("2080") =  1.603 ;
pm_emicapglob("2085") =  1.383 ;
pm_emicapglob("2090") =  1.206 ;
pm_emicapglob("2095") =  1.050 ;
pm_emicapglob("2100") =  0.938 ;
pm_emicapglob("2105") =  0.938 ;
pm_emicapglob("2110") =  0.938 ;
pm_emicapglob("2115") =  0.938 ;
pm_emicapglob("2120") =  0.938 ;
pm_emicapglob("2125") =  0.938 ;
pm_emicapglob("2130") =  0.938 ;
pm_emicapglob("2135") =  0.938 ;
pm_emicapglob("2140") =  0.938 ;
pm_emicapglob("2145") =  0.938 ;
pm_emicapglob("2150") =  0.938 ;

*** EOF ./modules/15_climate/magicc/input/p15_emicapglob_450.inc
