on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop
        
name: check

jobs:
  check:
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Remove .Rprofile
        run: rm .Rprofile

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          extra-repositories: https://rse.pik-potsdam.de/r/packages/

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::gms
          # piam packages also available on CRAN (madrat, magclass, citation,
          # gms, goxygen, GDPuc) will usually have an outdated binary version
          # available; by using extra-packages we get the newest version

      - name: codeCheck
        run: null <- gms::codeCheck(strict=TRUE)
        shell: Rscript {0}

      - name: fileSizeCheck
        run: source(".github/workflows/size-check")
        shell: Rscript {0}
